slam_toolbox:
  ros__parameters:
    mode: "mapping"
    debug_logging: false
    throttle_scans: 1
    base_frame: "base_link"
    map_frame: "map"
    odom_frame: "odom"
    map_update_interval: 5.0
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.02
    resolution: 0.05
    max_valid_laser_distance: 25.0
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.0
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.7
    loop_match_minimum_response_fine: 0.5